### ISSUE TITLE
`Dependency("package_jll", v"1.2.3")` results in inconsistent compat bounds

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilderBase.jl#45]
https://github.com/JuliaPackaging/Yggdrasil/pull/1718 Used the new syntax `Dependency("GMP_jll", v"6.1.2")`, which however results in inconsistent compat bounds between `Project.toml` and the registry:

* `Project.toml` has a strict dependency on `v6.1.2:` https://github.com/JuliaBinaryWrappers/Singular_jll.jl/blob/85929b66afd6fdd6b877ec60fe8de9fe12661b27/Project.toml#L18
* the registry has a lower bound compat on `v6.1.2`: https://github.com/JuliaRegistries/General/pull/22388/files#diff-190a13cffbbf470e5e0c7f62902925bcR2

The registry here is what we want and the only thing that actually matters, but it's probably better to make these two bounds consistent

**Comment by fingolfin** [comment]
I understood  @staticfloat as saying that the new syntax would not affect the compat versions. So did I misunderstand?

**Comment by staticfloat** [comment]
Probably there's a bug

**Comment by fingolfin** [comment]
I just tried building Singular_jll locally, using the latest git versions of `BinaryBuilderBase` and `BinaryBuilder` in latest Julia. The resulting `Project.toml` looks fine:
```toml
name = "Singular_jll"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "4.1.3+6"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
cddlib_jll = "f07e07eb-5685-515a-97c8-3014f6152feb"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
FLINT_jll = "e134572f-a0d5-539d-bddf-3cad8db41a82"

[compat]
JLLWrappers = "1.1.0"
julia = "1.0"
```

But in https://github.com/JuliaBinaryWrappers/Singular_jll.jl/blob/main/Project.toml we indeed see one extra unwanted line: `GMP_jll = "=6.1.2"`

Now, the feature under discussion was added in cab650c82efd15cf5676bc05b553c5fbcb7f1054 by modifying `getpkg` to inject the build version. That's the only place the `build_version` is ever access. So I assume either something is using `getpkg` which shouldn't; or else something is passing on the result of `getpkg` to a place where it shouldn't be used / where it eventually ends up in `Project.toml`.

As my experiment shows (modulo me screwing it up), just calling `build_tarballs.jl` works correctly. But AFAIK on Yggdrasil, the JLL wrapper actually is regenerated using `rebuild_jll_package`. So one guess would be that in this process the "bad" compat restriction somehow is injected, although I have no idea yet how that might happen. But perhaps it jogs a memory for @staticfloat or @giordano ?
